### ISSUE TITLE
Crashing with Bumblezone bee armor in 1.18.2

### ISSUE THREAD

**Issue by TelepathicGrunt** [apace100/cosmetic-armor#17] opened 2022-04-28 10:19 UTC
I have received this bug report:
https://github.com/TelepathicGrunt/Bumblezone-Fabric/issues/66

The issue the user reports is that when they add Bumblezone’s bee chest plate and then any other armor on while in 3rd person view, they get a crash with 3 mixins that show up in the stacktrace. I do not know exactly what is the cause or why the crash occurs. 

Could you please take a look and let me know if there’s anything on my end that is the cause or if this is something that cosmetic armor needs to fix? Thank you

How I register my armor models/textures:
https://github.com/TelepathicGrunt/Bumblezone-Fabric/blob/7ca6d8cce2b0802a6555a4c09e2f09ad0545c215/src/main/java/com/telepathicgrunt/the_bumblezone/items/BeeArmor.java#L37

https://github.com/TelepathicGrunt/Bumblezone-Fabric/blob/7ca6d8cce2b0802a6555a4c09e2f09ad0545c215/src/main/java/com/telepathicgrunt/the_bumblezone/client/BumblezoneClient.java#L88

https://github.com/TelepathicGrunt/Bumblezone-Fabric/blob/latest-released/src/main/java/com/telepathicgrunt/the_bumblezone/client/rendering/BeeArmorModel.java

**Comment by apace100** [comment] 2022-04-28 17:24
Thanks, I'll look into it and let you know.

**Comment by apace100** [comment] 2022-04-28 17:55
Can't reproduce this issue with Cosmetic Armor 1.3.0 and Bumblezone 5.0.10+1.18.2 on Minecraft 1.18.2.
Also, the most recent mixin in their crash log seems to be `handler$bnn000$getArmorTexture`, while Cosmetic Armor neither calls `getArmorTexture` nor mixes into it.
This must be some other mod chiming in.

**Comment by apace100** [comment] 2022-04-28 18:18
The problem is adding GeckoLib into the mix, similar to https://github.com/apace100/cosmetic-armor/issues/12.
I'll try to find a compatibility patch ASAP.

**Comment by apace100** [comment] 2022-04-28 19:39
Fixed with version 1.3.1 of Cosmetic Armor. If the problem persists, let me know and I'll reopen the issue. Sorry for the inconveniences!

**Closed as completed by apace100** 2022-04-28 19:39 UTC
